title: "Gyeongseop's Blog"
description: "딥러닝과 수학 공부를 정리합니다."
theme: minima

minima:
  skin: dark

markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap

# GitHub Pages 설정
baseurl: ""
url: "https://garylee87.github.io"
