title: "Gyeongseop's Blog"
description: "딥러닝과 수학 공부를 정리합니다."
theme: minima
markdown: kramdown
kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
    preview_as_code: false
  input: GFM
  syntax_highlighter: rouge

highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap

# MathJax 설정
mathjax: true

# GitHub Pages 설정
baseurl: ""
url: "https://garylee87.github.io"